const right_arrow = require('../assets/icons/right-arrow.png')
const email = require('../assets/icons/email.png')
const google = require('../assets/icons/google.png')
const user = require('../assets/icons/user.png')
const profileimage = require('../assets/icons/profileimage.png')
const upload = require('../assets/icons/upload.png')
const add = require('../assets/icons/add.png')
const camera = require('../assets/icons/camera.png')
const gallery = require('../assets/icons/gallery.png')
const remove = require('../assets/icons/remove.png')
const edit = require('../assets/icons/edit.png')
export default { email, right_arrow, google, user, profileimage, upload, add, camera, gallery, remove, edit };